config/routes.rb
Rails.application.routes.draw do

  resources :posts

  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get "login", to: 'users/sessions#new'
    get "logout", to: "users/sessions#destroy"
    get "sign_up", to: "users/registrations#new"
    get 'user_edit', to: 'users/registrations#edit'
    get 'profile', to: 'users/registrations#show'
  end

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user_id
  validates :content, :presence => { :message => 'no puedes postear con contenido vacio' }, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_paramaters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

    def configure_permitted_paramaters
      devise_parameter_sanitizer.for(:sign_up) { |a| a.permit(:user_name, :name, :birthday, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.for(:sign_in) { |a| a.permit(:user_name, :password, :remember_me)}
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :user_name, :name, :birthday)}
    end

  private
    def after_sign_in_path_for(resource)
     # After you enter login info and click submit, I want you to be sent to the registrations#show page
     # new_user_session_path
     # profile_path
     root_path
   end
   def after_sign_out_path_for(resource_or_scope)
     new_user_session_path
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: :edit

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = 'Post creado satisfactoriamente.'
      redirect_to profile_path
    else
      flash[:notice] = 'Post NO creado.'
      redirect_to profile_path
    end
  end

  def show
    @post
  end

  def edit
    @post
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post actualizado satisfactoriamente.'
      redirect_to profile_path
    else
      flash[:notice] = 'Post NO actualizado.'
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post eliminado satisfactoriamente.'
      redirect_to profile_path
    else
      flash[:notice] = 'Post NO eliminado.'
      redirect_to profile_path
    end
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content)
    end

    def require_permission
      if current_user != Post.find(params[:id]).user
        redirect_to profile_path
        
        #Or do something else here
      end
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy, :show]
  layout "sign_up", :only => [:new]
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  def show
    @posts = Post.where("posts.user_id = #{current_user.id}")
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  layout "sign_up"
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %nav
    -if user_signed_in?
      %span.label
        %strong= "Bienvenido #{current_user.name}"
      %span
        =link_to 'Perfil', profile_path
      %ul.nav.navbar-nav.navbar-right
        %li 
          =link_to 'Cerrar sesion', destroy_user_session_path, method: :delete
    -else
      %ul.nav.navbar-nav.navbar-right
        %li 
          =link_to 'login', login_path
        %li 
          =link_to 'Crear cuenta', sign_up_path


        

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => '//html5shiv.googlecode.com/svn/trunk/html5.js' }

app/views/layouts/application.html.haml
!!! 5
%html
%head
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = render 'layouts/shim'
%body

  = render 'layouts/header'
  .container
    .row
      -flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-info alert-#{message_type}")
    = yield
    = render 'layouts/footer'

app/views/layouts/sign_up.html.haml
!!! XML
!!! Strict
%html{ :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title= "Yummi exam login"
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :head
  %body.sessions
    .container
      .row
        -flash.each do |message_type, message|
          = content_tag(:div, message, class: "alert alert-info alert-#{message_type}")
    = yield

app/views/posts/edit.html.haml
.container
  .row
    .panel
      =form_for @post do |f|
        =f.text_area :content, {rows: 3, class: 'form-control'}
        %br
        = f.submit "Edit"

app/views/posts/show.html.haml
.container
  .row
    .col-md-4
      %h3
        Usuario
      %h4
        =@post.user.name
      %h4
        =@post.user.user_name
      %h4
        =@post.user.email
      %br
      =link_to 'Home', root_path
    .col-md-8
      .panel
        %table.table.table-striped
          %thead
            %tr
              %th
                Contenido
              %th
                Fecha de publicación
              %th{:colspan=>"3"}
          %tbody
            %tr
              %td
                =@post.content
              %td
                =@post.created_at

app/views/welcome/index.html.haml
.container
  .row
    .col-md-4
      %h3
        Bienvenido!
      %br
    .col-md-8
      %h3
        Post recientes
      .form-group
        - if @posts.count > 0
          - @posts.to_a.each do |post|
            .well
              .row
                %h4
                  %strong="Usuario #{post.user.user_name}"
              .row
                %strong=post.content
                %br
                =link_to 'Mostrar', post
        - else
          %h3
            No hay post que revisar.

        